"""
Test provenance header injection in generated code.
"""
import pytest
from shieldcraft.services.checklist.generator import ChecklistGenerator
from shieldcraft.services.codegen.generator import CodeGenerator


def test_provenance_header_contains_lineage_id():
    """Test that generated code contains Lineage ID in header."""
    spec = {
        "metadata": {
            "product_id": "test",
            "version": "1.0"
        },
        "model": {
            "modules": [
                {
                    "name": "ProvenanceTestModule",
                    "type": "module",
                    "dependencies": []
                }
            ]
        },
        "sections": []
    }
    
    # Build checklist
    generator = ChecklistGenerator()
    checklist_result = generator.build(spec)
    items = checklist_result["items"]
    
    # Run codegen
    codegen = CodeGenerator()
    outputs = codegen.run({"items": items})
    
    # Find module output
    module_outputs = [out for out in outputs if "modules" in out.get("path", "")]
    assert len(module_outputs) > 0, "No module outputs found"
    
    # Check header
    content = module_outputs[0]["content"]
    assert "# Generated by ShieldCraft Engine" in content
    assert "# Lineage ID:" in content
    assert "# Source Pointer:" in content
    assert "# Source Node Type:" in content


def test_provenance_header_format():
    """Test that provenance header follows correct format."""
    spec = {
        "metadata": {
            "product_id": "test",
            "version": "1.0"
        },
        "sections": [
            {
                "id": "sec1",
                "name": "Test Section",
                "items": [
                    {
                        "id": "item1",
                        "text": "Test item",
                        "severity": "high",
                        "output": "test_output.txt",
                        "template": "default"
                    }
                ]
            }
        ]
    }
    
    # Build checklist
    generator = ChecklistGenerator()
    checklist_result = generator.build(spec)
    items = checklist_result["items"]
    
    # Run codegen
    codegen = CodeGenerator()
    outputs = codegen.run({"items": items})
    
    # Check that all outputs have proper header
    for output in outputs:
        content = output.get("content", "")
        
        # Should start with comment header
        lines = content.split("\n")
        assert lines[0].startswith("#"), "First line should be comment"
        
        # Should contain lineage metadata
        header_section = "\n".join(lines[:10])  # First 10 lines
        assert "Lineage ID:" in header_section or "Source Pointer:" in header_section


def test_provenance_includes_source_pointer():
    """Test that provenance header includes source pointer from spec."""
    spec = {
        "metadata": {
            "product_id": "test",
            "version": "1.0"
        },
        "sections": [
            {
                "id": "sec_alpha",
                "name": "Alpha Section",
                "items": [
                    {
                        "id": "item_alpha",
                        "text": "Alpha item",
                        "severity": "high",
                        "output": "alpha_output.txt",
                        "template": "default"
                    }
                ]
            }
        ]
    }
    
    # Build checklist
    generator = ChecklistGenerator()
    checklist_result = generator.build(spec)
    items = checklist_result["items"]
    
    # Run codegen
    codegen = CodeGenerator()
    outputs = codegen.run({"items": items})
    
    # Verify source pointer is in header
    for output in outputs:
        content = output.get("content", "")
        if "alpha" in output.get("path", "").lower():
            assert "Source Pointer:" in content
            assert "/sections/0/items/0" in content  # Expected pointer for first item


def test_provenance_lineage_id_not_unknown():
    """Test that lineage_id in header is not 'unknown'."""
    spec = {
        "metadata": {
            "product_id": "test",
            "version": "1.0"
        },
        "model": {
            "modules": [
                {
                    "name": "ValidLineageModule",
                    "type": "module",
                    "dependencies": []
                }
            ]
        },
        "sections": []
    }
    
    # Build checklist
    generator = ChecklistGenerator()
    checklist_result = generator.build(spec)
    items = checklist_result["items"]
    
    # Run codegen
    codegen = CodeGenerator()
    outputs = codegen.run({"items": items})
    
    # Check that lineage_id is not 'unknown'
    for output in outputs:
        content = output.get("content", "")
        if "# Lineage ID:" in content:
            # Extract lineage ID line
            for line in content.split("\n"):
                if "# Lineage ID:" in line:
                    lineage_value = line.split("# Lineage ID:")[1].strip()
                    assert lineage_value != "unknown", f"Lineage ID should not be 'unknown': {lineage_value}"
                    # Should be a hash (SHA256 = 64 chars)
                    assert len(lineage_value) == 64, f"Lineage ID should be SHA256 hash: {lineage_value}"
